name = "photo-converter"
compatibility_flags = [ "nodejs_compat" ]

# Pages configuration
[site]
bucket = "./out"
pages_build_output_dir = "out"

# Environment variables if needed
[vars]
NODE_VERSION = "20"

[build]
command = "npm run build"